"""empty message

Revision ID: 499f18705e8c
Revises: None
Create Date: 2014-09-24 18:55:39.602000

"""

# revision identifiers, used by Alembic.
revision = '499f18705e8c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
